### ISSUE TITLE
How big of a buffer would be needed to support the entire godot vertex format?

### ISSUE THREAD

**Issue by fire** [gamma-delta/HelloComputeGeometry#1]
Curious

**Comment by gamma-delta** [comment]
https://docs.godotengine.org/en/stable/classes/class_mesh.html#enumerations

I think the default Godot vertex format is vec3 position, vec3 normal, vec4 tangent, vec2 UV, vec4 color. If you compressed the UV into the w coordinate of the position and normal, that would be 16 bytes a vertex. Otherwise, it'd be 20 bytes, because you'd need padding bytes for position, normal, and UV.

**Comment by fire** [comment]
There are 8 uvs. So this cannot be correct.

**Comment by fire** [comment]
I made a chart.

| Array Type       | Description                                                                                                      | Size in Floats |
|------------------|------------------------------------------------------------------------------------------------------------------|----------------|
| ARRAY_VERTEX     | [PackedVector3Array](https://docs.godotengine.org/en/stable/classes/class_packedvector3array.html#class-packedvector3array), [PackedVector2Array](https://docs.godotengine.org/en/stable/classes/class_packedvector2array.html#class-packedvector2array), or [Array](https://docs.godotengine.org/en/stable/classes/class_array.html#class-array) of vertex positions. | 3 (Vector3) or 2 (Vector2) |
| ARRAY_NORMAL     | [PackedVector3Array](https://docs.godotengine.org/en/stable/classes/class_packedvector3array.html#class-packedvector3array) of vertex normals. Can be compressed into an octahedral compressed vector 2. | 3 or 2         |
| ARRAY_TANGENT    | [PackedFloat32Array](https://docs.godotengine.org/en/stable/classes/class_packedfloat32array.html#class-packedfloat32array) of vertex tangents. Each element in groups of 4 floats, first 3 floats determine the tangent, and the last the binormal direction as -1 or 1. | 4              |
| ARRAY_COLOR      | [PackedColorArray](https://docs.godotengine.org/en/stable/classes/class_packedcolorarray.html#class-packedcolorarray) of vertex colors. | 4              |
| ARRAY_TEX_UV     | [PackedVector2Array](https://docs.godotengine.org/en/stable/classes/class_packedvector2array.html#class-packedvector2array) for UV coordinates. | 2              |
| ARRAY_TEX_UV2    | [PackedVector2Array](https://docs.godotengine.org/en/stable/classes/class_packedvector2array.html#class-packedvector2array) for second UV coordinates. | 2              |
| ARRAY_CUSTOM0    | Contains custom data. Typically [PackedFloat32Array](https://docs.godotengine.org/en/stable/classes/class_packedfloat32array.html#class-packedfloat32array) with 4 floats per vertex, but can vary. | 4 (commonly)   |
| ARRAY_CUSTOM1    | Contains custom data. Typically [PackedFloat32Array](https://docs.godotengine.org/en/stable/classes/class_packedfloat32array.html#class-packedfloat32array) with 4 floats per vertex, but can vary. | 4 (commonly)   |
| ARRAY_CUSTOM2    | Contains custom data. Typically [PackedFloat32Array](https://docs.godotengine.org/en/stable/classes/class_packedfloat32array.html#class-packedfloat32array) with 4 floats per vertex, but can vary. | 4 (commonly)   |
| ARRAY_CUSTOM3    | Contains custom data. Typically [PackedFloat32Array](https://docs.godotengine.org/en/stable/classes/class_packedfloat32array.html#class-packedfloat32array) with 4 floats per vertex, but can vary. | 4 (commonly)   |
| ARRAY_BONES      | [PackedFloat32Array](https://docs.godotengine.org/en/stable/classes/class_packedfloat32array.html#class-packedfloat32array) or [PackedInt32Array](https://docs.godotengine.org/en/stable/classes/class_packedint32array.html#class-packedint32array) of bone indices. Contains either 4 or 8 numbers per vertex depending on the presence of the [ARRAY_FLAG_USE_8_BONE_WEIGHTS](https://docs.godotengine.org/en/stable/classes/class_mesh.html#class-mesh-constant-array-flag-use-8-bone-weights) flag. | 4 or 8         |
| ARRAY_WEIGHTS    | [PackedFloat32Array](https://docs.godotengine.org/en/stable/classes/class_packedfloat32array.html#class-packedfloat32array) or [PackedFloat64Array](https://docs.godotengine.org/en/stable/classes/class_packedfloat64array.html#class-packedfloat64array) of bone weights in the range 0.0 to 1.0 (inclusive). Contains either 4 or 8 numbers per vertex depending on the presence of the [ARRAY_FLAG_USE_8_BONE_WEIGHTS](https://docs.godotengine.org/en/stable/classes/class_mesh.html#class-mesh-constant-array-flag-use-8-bone-weights) flag. | 4 or 8         |
| ARRAY_INDEX      | [PackedInt32Array](https://docs.godotengine.org/en/stable/classes/class_packedint32array.html#class-packedint32array) of integers used as indices referencing vertices, colors, normals, tangents, and textures. | 1 (per index)  |
| ARRAY_MAX        | Represents the size of the [ArrayType](https://docs.godotengine.org/en/stable/classes/class_mesh.html#enum-mesh-arraytype) enum. | N/A            |
| **Total**        | **Sum of all sizes in floats (assuming common values where applicable)**                                          | **47 or 51**   |
